server:
  port: 8080

jwt:
  expiration_time: 864000000
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey


http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true


## DataSource type Configuration
# DataSource 구현체 명시적으로 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # MySQL 서버의 시간대 설정 (기준시: UTC, 한국: Asia/Seoul)
    url : jdbc:mysql://gyeongjin.cxjusor1qp7q.ap-northeast-2.rds.amazonaws.com:3306/my_rds_db?serverTimezone=UTC
    username: admin
    password: rktlskan2!
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true

  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**
  show-login-endpoint: true



